// src/components/Statistics.tsx
import { BarChart } from './BarChart'
import {MatchResult} from '../core/matcher'
import {FunctionComponent} from 'react'

type Props = {
    result: MatchResult
}


export const Statistics:FunctionComponent<Props> = ({ result }) => {
    const getXLabel = (priority: number) => `${priority + 1}. Priorität`
    const computePriorityDistribution = (results: MatchResult): number[] => {
        const distribution: Record<string, number> = {}
        for (const activity of results.activities) {
            for (const participant of activity.participants) {
                const fullfilledPriority = participant.priorities.indexOf(activity.id)
                if (!distribution[getXLabel(fullfilledPriority)]) {
                    distribution[getXLabel(fullfilledPriority)] = 1
                } else {
                    distribution[getXLabel(fullfilledPriority)]++
                }
            }
        }
        return Object.keys(distribution).map(priority => distribution[priority])
    }
    return (
        <div id="statistics-root">
            <div id="statistics-overview">
                <h3>Zusammenfassung</h3>
                <table>
                    <thead>
                        <tr>
                            <th/>
                            <th>Zugewiesen</th>
                            <th>Minimum</th>
                            <th>Limit</th>
                        </tr>
                    </thead>
                    <tbody>
                        {result.activities.map((activity) => (
                            <tr key={`activity-${activity.id}`}>
                                <td>{activity.title}</td>
                                <td className="number">
                                    {activity.participants.length}
                                </td>
                                <td className="number">{activity.minimum}</td>
                                <td className="number">{activity.limit}</td>
                            </tr>
                        ))}
                        <tr className="totals">
                            <td>Total</td>
                            <td className="number">
                                {
                                    result.participants.filter(
                                        (student) => student.assigned
                                    ).length
                                }
                            </td>
                            <td className="number">
                                {result.activities
                                    .map((course) => course.minimum)
                                    .reduce(
                                        (partialSum, minimum) =>
                                            partialSum + minimum
                                    )}
                            </td>
                            <td className="number">
                                {result.activities
                                    .map((course) => course.limit)
                                    .reduce(
                                        (partialSum, limit) =>
                                            partialSum + limit
                                    )}
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div id="statistics-barchart">
                <h3>Verteilung der erf&uuml;llten Priorit&auml;ten</h3>
                <BarChart fulfilledPriorities={computePriorityDistribution(result)} totalParticipants={result.participants.length} />
            </div>
        </div>
    )
}

// src/gui/components/Statistics.vue
<template>
    <div id="statistics-root">
        <div id="statistics-overview">
            <h3>Zusammenfassung</h3>
            <table>
                <thead>
                    <tr>
                        <th></th>
                        <th>Zugewiesen</th>
                        <th>Minimum</th>
                        <th>Limit</th>
                    </tr>
                </thead>
                <tbody>
                    <tr v-for="course in result.courses">
                        <td>{{ course.name }}</td>
                        <td class="number">{{ course.students.length }}</td>
                        <td class="number">{{ course.minimum }}</td>
                        <td class="number">{{ course.limit }}</td>
                    </tr>
                    <tr class="totals">
                        <td>Total</td>
                        <td class="number">
                            {{
                                result.students.filter(
                                    (student) => student.matched
                                ).length
                            }}
                        </td>
                        <td class="number">
                            {{
                                result.courses
                                    .map((course) => course.minimum)
                                    .reduce(
                                        (partialSum, minimum) =>
                                            partialSum + minimum
                                    )
                            }}
                        </td>
                        <td class="number">
                            {{
                                result.courses
                                    .map((course) => course.limit)
                                    .reduce(
                                        (partialSum, limit) =>
                                            partialSum + limit
                                    )
                            }}
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div id="statistics-barchart">
            <h3>Verteilung der erf&uuml;llten Priorit&auml;ten</h3>
            <BarChart :data="computePriorityDistribution(result)" />
        </div>
    </div>
</template>
<script>
import BarChart from '@/gui/components/BarChart'

const getXLabel = (priority) => `${priority + 1}. Priorität`

export default {
    components: { BarChart },
    name: 'Statistics',
    props: ['result'],
    methods: {
        computePriorityDistribution(results) {
            const distribution = {}
            for (const course of results.courses) {
                for (const student of course.students) {
                    const fullfilledPriority = student.priorities.indexOf(
                        course.id
                    )
                    if (!distribution[getXLabel(fullfilledPriority)]) {
                        distribution[getXLabel(fullfilledPriority)] = 1
                    } else {
                        distribution[getXLabel(fullfilledPriority)]++
                    }
                }
            }
            console.log(distribution)
            return distribution
        }
    }
}
</script>
<style scoped>
table {
    border-spacing: 0;
    min-width: 350px;
    max-width: 550px;
}

tr.totals {
    font-weight: bold;
}

table tr td,
th {
    padding: 0.3em;
}

td.number {
    text-align: center;
}

table tbody tr:nth-of-type(even) {
    background-color: #ddd;
}

ul {
    margin: 0;
    padding: 0;
    list-style: none;
}

#statistics-root {
    display: grid;
    grid-column-gap: 20px;
    grid-template-areas: 'overview barchart';
}

#statistics-overview {
    grid-area: overview;
}

#statistics-barchart {
    grid-area: barchart;
}
</style>
